services:

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: Starter.Uptime-Kuma
    ports:
      - "3001:3001"
    volumes:
      - uptimekuma-data:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kuma-https.entrypoints=https"
      - "traefik.http.routers.kuma-https.rule=Host(`kuma.webport.co.za`)"
      - "traefik.http.routers.kuma-https.tls=true"
      - "traefik.http.routers.kuma-https.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.services.kuma.loadbalancer.server.port=3001"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  uptimekuma-data: