services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.1.1
    container_name: homepage-container
    ports:
      - 3000:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    environment:
      HOMEPAGE_ALLOWED_HOSTS: dashboard.webport.co.za
      #PUID: 1026 # optional, your user id
      #PGID: 100 # optional, your group id
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.routers.homepage.entrypoints=https"
      - "traefik.http.routers.homepage.rule=Host(`dashboard.webport.co.za`)"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.routers.homepage.tls.certresolver=cloudflare"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
    networks:
      - proxy

networks:
  proxy:
    external: true
