services:
  ftp-server:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      USERS: ftpuser|25122000@Saif|/home/ftpuser
    volumes:
      - ./ftp:/home/ftpuser


