apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webport-certificate
  namespace: default
spec:
  secretName: webport-certificate-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "webport.co.za"
    - "*.webport.co.za"
  issuerRef:
    name: cluster-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io