apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-prod
spec:
  acme:
    email: saifdev22@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-secret-key
    solvers:
    - dns01:
        cloudflare:
          email: saifdev22@gmail.com
          apiTokenSecretRef:
            name: cloudflare-token-secret
            key: api-token
      selector:
        dnsZones:
        - 'webport.co.za'
        - '*.webport.co.za'