name: Blazor Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - src/clients/BlazorMaster/**
      - src/api/Client.API/**
 
jobs:
  build_images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: Build and push with Docker Compose
        run: |
          docker compose -f docker-compose.client.yml build
          docker compose -f docker-compose.client.yml push
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: '${{ secrets.DOCKERHUB_USERNAME }}'
          
  copy_files:
    name: Copy files to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: '${{ secrets.SERVER_HOST }}'
          username: '${{ secrets.SERVER_USERNAME }}'
          key: '${{ secrets.SERVER_SSH_KEY}}'
          source: docker-compose.client.yml
          target: /home/BlazorClient
          
  update_server:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build_images
    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SERVER_HOST }}'
          username: '${{ secrets.SERVER_USERNAME }}'
          key: '${{ secrets.SERVER_SSH_KEY }}'
          script: |
            cd /home/BlazorClient
            docker-compose -f docker-compose.client.yml down || true
            docker image prune -a -f
            docker-compose -f docker-compose.client.yml pull
            docker-compose -f docker-compose.client.yml up -d 
