services:
  
  postgresql.database:
    image: postgres:17
    container_name: postgresql-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=25122000SK
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

volumes:
  postgres_data:

networks:
  proxy:
    external: true